// ── PHONETICS DATA ────────────────────────────────────────────────────

export const VOWEL_SOUNDS = [
  {
    ipa: "iː",
    name: "Long EE",
    spelling: "ee, ea, e, ie, ey",
    mouth: "Lips spread wide, tongue high and forward.",
    words: ["feet", "sea", "me", "believe", "key"],
    minimal: ["ship / sheep", "bit / beat", "fill / feel"],
    trap: "Don't cut it short — 'ship' and 'sheep' are different words.",
  },
  {
    ipa: "ɪ",
    name: "Short I",
    spelling: "i, y, ui, e",
    mouth: "Lips slightly spread, tongue high but relaxed.",
    words: ["sit", "gym", "build", "women"],
    minimal: ["sit / seat", "bit / beat", "fill / feel"],
    trap: "Common error: saying 'sheep' when you mean 'ship'.",
  },
  {
    ipa: "e",
    name: "Short E",
    spelling: "e, ea, a",
    mouth: "Mouth half open, lips slightly spread.",
    words: ["bed", "head", "any"],
    minimal: ["bed / bad", "pen / pan", "get / gut"],
    trap: "Don't confuse with /æ/ — 'bed' and 'bad' mean different things.",
  },
  {
    ipa: "æ",
    name: "Short A",
    spelling: "a",
    mouth: "Mouth open wide, tongue low and forward — say 'ah' then smile.",
    words: ["cat", "man", "happy", "apple"],
    minimal: ["cat / cut", "bad / bed", "pan / pen"],
    trap: "Canadian/American English — this sound is very open. Don't raise it to /e/.",
  },
  {
    ipa: "ɑː",
    name: "Long AH",
    spelling: "a, ar, o",
    mouth: "Jaw dropped, tongue low and back, mouth wide open.",
    words: ["father", "car", "hot", "palm"],
    minimal: ["cot / coat", "calm / come"],
    trap: "In Canadian English, 'cot' and 'caught' often sound the same (cot-caught merger).",
  },
  {
    ipa: "ɔː",
    name: "Long AW",
    spelling: "aw, au, or, oor, al",
    mouth: "Lips rounded, mouth half open, tongue back.",
    words: ["law", "cause", "more", "floor", "all"],
    minimal: ["caught / cot", "saw / so", "law / low"],
    trap: "Many Canadian speakers merge this with /ɑː/ — context helps distinguish.",
  },
  {
    ipa: "ʊ",
    name: "Short OO",
    spelling: "u, oo, ou",
    mouth: "Lips loosely rounded, tongue high and back but relaxed.",
    words: ["book", "put", "could", "wolf"],
    minimal: ["book / boot", "pull / pool", "full / fool"],
    trap: "Don't use the full long /uː/ — 'book' is short and relaxed.",
  },
  {
    ipa: "uː",
    name: "Long OO",
    spelling: "oo, u, ew, ue, ou",
    mouth: "Lips tightly rounded and pushed forward, tongue high and back.",
    words: ["food", "rule", "new", "blue", "soup"],
    minimal: ["fool / full", "pool / pull", "boot / book"],
    trap: "Hold the sound longer than /ʊ/ — it's a tense, sustained sound.",
  },
  {
    ipa: "ʌ",
    name: "Short U",
    spelling: "u, o, ou, oo",
    mouth: "Mouth half open, tongue in centre, lips neutral.",
    words: ["cup", "come", "young", "flood"],
    minimal: ["cup / cap", "cut / cat", "gun / gone"],
    trap: "This is the most common vowel sound in English — also found in unstressed syllables.",
  },
  {
    ipa: "ə",
    name: "Schwa",
    spelling: "any vowel (unstressed)",
    mouth: "Mouth relaxed, tongue central — the laziest vowel sound.",
    words: ["about", "sofa", "taken", "famous", "pencil"],
    minimal: ["above / a-bove (stress shift)", "photograph / photography"],
    trap: "The schwa ONLY appears in unstressed syllables. It's the most common sound in English.",
  },
  {
    ipa: "eɪ",
    name: "Long A",
    spelling: "a, ai, ay, ea, ey",
    mouth:
      "Start with /e/ then glide toward /ɪ/ — it's a diphthong (two sounds).",
    words: ["face", "rain", "day", "great", "they"],
    minimal: ["face / fuss", "late / let", "say / so"],
    trap: "It's a glide — don't hold it flat. The mouth moves from open to closed.",
  },
  {
    ipa: "oʊ",
    name: "Long O",
    spelling: "o, oa, ow, oe",
    mouth: "Start with /o/ then glide toward /ʊ/ — lips round and close.",
    words: ["go", "boat", "know", "toe"],
    minimal: ["go / goo", "coat / cut", "low / law"],
    trap: "In American/Canadian English this is a diphthong — don't say a flat 'oh'.",
  },
  {
    ipa: "aɪ",
    name: "Long I",
    spelling: "i, igh, y, ie, uy",
    mouth: "Start open /ɑ/ then glide up to /ɪ/ — wide movement.",
    words: ["time", "high", "my", "pie", "buy"],
    minimal: ["time / team", "ride / read", "mine / mean"],
    trap: "A clear diphthong — both parts must be audible or it sounds like /ɑː/.",
  },
  {
    ipa: "aʊ",
    name: "OW sound",
    spelling: "ou, ow",
    mouth: "Start open /ɑ/ then round lips toward /ʊ/.",
    words: ["out", "now", "house", "cow"],
    minimal: ["out / oat", "cow / coat", "found / fond"],
    trap: "In Canadian English this is noticeably different before voiceless consonants — 'about' vs 'out'.",
  },
  {
    ipa: "ɔɪ",
    name: "OY sound",
    spelling: "oi, oy",
    mouth: "Start rounded /ɔ/ then glide to /ɪ/.",
    words: ["boy", "coin", "joy", "noise"],
    minimal: ["coin / con", "boy / bay"],
    trap: "Don't flatten it — both parts of the diphthong should be clear.",
  },
];

export const CONSONANT_SOUNDS = [
  {
    ipa: "p",
    name: "P",
    type: "Stop",
    voiced: false,
    spelling: "p, pp",
    mouth: "Lips pressed together, then released with a puff of air.",
    words: ["pen", "apple", "cap"],
    pair: "b",
    tip: "At the start of a word, English /p/ has a strong puff of air (aspiration): 'pin' vs 'bin'.",
  },
  {
    ipa: "b",
    name: "B",
    type: "Stop",
    voiced: true,
    spelling: "b, bb",
    mouth:
      "Lips pressed together, released — but voice is on (feel throat vibrate).",
    words: ["bed", "abbey", "cab"],
    pair: "p",
    tip: "At the end of words, the final /b/ is often unreleased — lips close but don't pop.",
  },
  {
    ipa: "t",
    name: "T",
    type: "Stop",
    voiced: false,
    spelling: "t, tt, ed",
    mouth: "Tongue tip touches the ridge behind upper teeth, then releases.",
    words: ["top", "butter", "cat"],
    pair: "d",
    tip: "In North American English, /t/ between vowels often sounds like a quick /d/ (flap): 'butter' → 'budder'.",
  },
  {
    ipa: "d",
    name: "D",
    type: "Stop",
    voiced: true,
    spelling: "d, dd, ed",
    mouth: "Same position as /t/ but with voice.",
    words: ["dog", "ladder", "bad"],
    pair: "t",
    tip: "Past tense -ed is /d/ after voiced sounds: 'called', 'played', 'loved'.",
  },
  {
    ipa: "k",
    name: "K",
    type: "Stop",
    voiced: false,
    spelling: "k, c, ck, ch, qu",
    mouth: "Back of tongue touches soft palate, then releases.",
    words: ["cat", "king", "back", "school"],
    pair: "g",
    tip: "Silent 'k' before 'n': know, knock, knife.",
  },
  {
    ipa: "g",
    name: "G",
    type: "Stop",
    voiced: true,
    spelling: "g, gg, gh",
    mouth: "Same as /k/ but with voice.",
    words: ["go", "egg", "ghost"],
    pair: "k",
    tip: "'gh' is usually silent: through, though, night, right.",
  },
  {
    ipa: "f",
    name: "F",
    type: "Fricative",
    voiced: false,
    spelling: "f, ff, ph, gh",
    mouth: "Upper teeth lightly touch lower lip, air flows through.",
    words: ["fish", "off", "phone", "enough"],
    pair: "v",
    tip: "'ph' always makes /f/ in English: phone, photo, graph.",
  },
  {
    ipa: "v",
    name: "V",
    type: "Fricative",
    voiced: true,
    spelling: "v, f (of)",
    mouth: "Same as /f/ but with voice — feel the vibration on your lip.",
    words: ["very", "love", "of"],
    pair: "f",
    tip: "The word 'of' is pronounced /ʌv/ — the f is voiced.",
  },
  {
    ipa: "θ",
    name: "TH (voiceless)",
    type: "Fricative",
    voiced: false,
    spelling: "th",
    mouth: "Tongue tip lightly between or behind upper teeth, air flows out.",
    words: ["think", "bath", "three", "both"],
    pair: "ð",
    tip: "One of the hardest sounds for non-native speakers. Tongue must touch teeth — not /t/ or /s/.",
  },
  {
    ipa: "ð",
    name: "TH (voiced)",
    type: "Fricative",
    voiced: true,
    spelling: "th",
    mouth: "Same as /θ/ but with voice — feel vibration.",
    words: ["the", "this", "that", "mother", "breathe"],
    pair: "θ",
    tip: "Function words (the, this, that, they, them) use voiced /ð/. Content words often use voiceless /θ/.",
  },
  {
    ipa: "s",
    name: "S",
    type: "Fricative",
    voiced: false,
    spelling: "s, ss, c, sc",
    mouth: "Tongue near ridge behind teeth, air creates a hiss.",
    words: ["sit", "pass", "city", "scene"],
    pair: "z",
    tip: "Plural -s and possessive -s are /s/ after voiceless sounds: cats, books, cups.",
  },
  {
    ipa: "z",
    name: "Z",
    type: "Fricative",
    voiced: true,
    spelling: "z, zz, s, x",
    mouth: "Same as /s/ but with voice.",
    words: ["zoo", "jazz", "is", "exact"],
    pair: "s",
    tip: "Plural -s and possessive -s are /z/ after voiced sounds: dogs, cars, trees.",
  },
  {
    ipa: "ʃ",
    name: "SH",
    type: "Fricative",
    voiced: false,
    spelling: "sh, ti, ci, ch, si",
    mouth: "Lips slightly rounded, tongue raised — a wide hiss.",
    words: ["she", "nation", "special", "chef", "mission"],
    pair: "ʒ",
    tip: "Very common in English endings: -tion, -sion, -cial, -tial all use /ʃ/.",
  },
  {
    ipa: "ʒ",
    name: "ZH",
    type: "Fricative",
    voiced: true,
    spelling: "si, ge, s",
    mouth: "Same as /ʃ/ but with voice.",
    words: ["measure", "genre", "vision", "beige"],
    pair: "ʃ",
    tip: "Rare in English — mainly in borrowed French words and -sion/-sure endings.",
  },
  {
    ipa: "tʃ",
    name: "CH",
    type: "Affricate",
    voiced: false,
    spelling: "ch, tch, t",
    mouth: "Start with /t/ then release into /ʃ/ — a combined sound.",
    words: ["chair", "watch", "nature"],
    pair: "dʒ",
    tip: "Don't separate into t+sh — it's one flowing sound.",
  },
  {
    ipa: "dʒ",
    name: "J",
    type: "Affricate",
    voiced: true,
    spelling: "j, g, dge, d",
    mouth: "Start with /d/ then release into /ʒ/.",
    words: ["jump", "gem", "bridge", "soldier"],
    pair: "tʃ",
    tip: "'g' before e/i/y is usually /dʒ/: gym, gem, giraffe. But: get, give = /g/.",
  },
  {
    ipa: "m",
    name: "M",
    type: "Nasal",
    voiced: true,
    spelling: "m, mm, mb",
    mouth: "Lips closed, air flows through the nose.",
    words: ["man", "summer", "lamb"],
    pair: null,
    tip: "Silent 'mb' at the end of words: lamb, comb, bomb, thumb.",
  },
  {
    ipa: "n",
    name: "N",
    type: "Nasal",
    voiced: true,
    spelling: "n, nn, kn, gn",
    mouth: "Tongue tip on ridge behind upper teeth, air through nose.",
    words: ["no", "dinner", "know", "gnome"],
    pair: null,
    tip: "Silent 'kn' at the start: know, knife, knock, knee.",
  },
  {
    ipa: "ŋ",
    name: "NG",
    type: "Nasal",
    voiced: true,
    spelling: "ng, n (before k/g)",
    mouth: "Back of tongue on soft palate, air through nose — no /g/ release.",
    words: ["sing", "ring", "think", "bank"],
    pair: null,
    tip: "No /g/ sound after -ng in most words: sing = /sɪŋ/ not /sɪŋg/. But: finger, angry do have /g/.",
  },
  {
    ipa: "l",
    name: "L",
    type: "Lateral",
    voiced: true,
    spelling: "l, ll",
    mouth: "Tongue tip on ridge, air flows around the sides.",
    words: ["light", "ball", "milk"],
    pair: null,
    tip: "Clear /l/ at start of syllables. Dark /l/ (tongue pulled back) at end: feel, ball, milk.",
  },
  {
    ipa: "r",
    name: "R",
    type: "Approximant",
    voiced: true,
    spelling: "r, rr, wr",
    mouth: "Tongue curls back, never touches the roof — lips slightly rounded.",
    words: ["red", "carry", "write"],
    pair: null,
    tip: "North American /r/ is 'rhotic' — always pronounced, even after vowels: car, bird, her.",
  },
  {
    ipa: "j",
    name: "Y",
    type: "Approximant",
    voiced: true,
    spelling: "y, i, j (in some words)",
    mouth: "Tongue high and forward, glides quickly to the next sound.",
    words: ["yes", "you", "beyond", "few (=fyoo)"],
    pair: null,
    tip: "Many words starting with 'u' use /j/: use = /juːz/, union = /juːniən/.",
  },
  {
    ipa: "w",
    name: "W",
    type: "Approximant",
    voiced: true,
    spelling: "w, wh, u (after q)",
    mouth: "Lips tightly rounded then release into the next vowel.",
    words: ["wet", "when", "quick"],
    pair: null,
    tip: "Silent 'w' in: write, wrap, wrist, wrong — and in 'who', 'whole'.",
  },
  {
    ipa: "h",
    name: "H",
    type: "Fricative",
    voiced: false,
    spelling: "h, wh",
    mouth: "Mouth open in position of next vowel, air rushes out.",
    words: ["hat", "who", "ahead"],
    pair: null,
    tip: "Silent 'h' in: hour, honest, heir, honour — and in unstressed 'him/her/have' mid-sentence.",
  },
];

export const STRESS_RULES = [
  {
    rule: "Two-syllable nouns & adjectives",
    pattern: "Stress on the FIRST syllable",
    examples: [
      { word: "PREsent", note: "noun/adjective" },
      { word: "TAble", note: "" },
      { word: "HAPpy", note: "" },
      { word: "CLEver", note: "" },
    ],
    tip: "Most two-syllable nouns and adjectives follow this pattern.",
  },
  {
    rule: "Two-syllable verbs",
    pattern: "Stress on the SECOND syllable",
    examples: [
      { word: "preSENT", note: "verb" },
      { word: "reLAX", note: "" },
      { word: "deCIDE", note: "" },
      { word: "beGIN", note: "" },
    ],
    tip: "Noun/verb pairs shift stress: REcord (noun) → reCORD (verb). PERmit → perMIT.",
  },
  {
    rule: "Words ending in -ic, -ical",
    pattern: "Stress on syllable BEFORE the suffix",
    examples: [
      { word: "photoGRAPHic", note: "" },
      { word: "econOMic", note: "" },
      { word: "gramMAtical", note: "" },
    ],
    tip: "",
  },
  {
    rule: "Words ending in -tion, -sion",
    pattern: "Stress on syllable BEFORE the suffix",
    examples: [
      { word: "inforMAtion", note: "" },
      { word: "commuNIcation", note: "" },
      { word: "deCIsion", note: "" },
    ],
    tip: "The -tion ending is always pronounced /ʃən/ — never /tiːɒn/.",
  },
  {
    rule: "Words ending in -ity, -ety, -ity",
    pattern: "Stress on syllable BEFORE the suffix",
    examples: [
      { word: "posSIbility", note: "" },
      { word: "comMUnity", note: "" },
      { word: "anxiEty", note: "" },
    ],
    tip: "",
  },
  {
    rule: "Compound nouns",
    pattern: "Stress on the FIRST word",
    examples: [
      { word: "BLACKbird", note: "vs. black BIRD (any black bird)" },
      { word: "GREENhouse", note: "" },
      { word: "AIRport", note: "" },
    ],
    tip: "Compound nouns have one primary stress on the first element. Noun phrases stress the second.",
  },
  {
    rule: "Prefixes",
    pattern: "Usually NO stress on the prefix",
    examples: [
      { word: "unHAPpy", note: "" },
      { word: "rePEAT", note: "" },
      { word: "disCOVer", note: "" },
    ],
    tip: "Exceptions: some prefixes carry stress in nouns: EX-wife, CO-worker.",
  },
];

export const CONNECTED_SPEECH = [
  {
    feature: "Linking",
    emoji: "🔗",
    description:
      "When a word ends in a consonant and the next begins with a vowel, they link together as if one word.",
    examples: [
      {
        phrase: "pick it up",
        linked: "pi-ki-tup",
        note: "consonant + vowel linking",
      },
      { phrase: "turn off", linked: "tur-noff", note: "" },
      { phrase: "an apple", linked: "a-napple", note: "" },
    ],
  },
  {
    feature: "Elision",
    emoji: "✂️",
    description:
      "Sounds are dropped in fast speech, especially /t/ and /d/ between consonants.",
    examples: [
      { phrase: "last night", linked: "las' night", note: "/t/ dropped" },
      { phrase: "next day", linked: "nex' day", note: "/t/ dropped" },
      { phrase: "hold on", linked: "hol' on", note: "/d/ dropped" },
    ],
  },
  {
    feature: "Assimilation",
    emoji: "🔄",
    description: "A sound changes to become more like a neighbouring sound.",
    examples: [
      { phrase: "ten pins", linked: "tem pins", note: "/n/ → /m/ before /p/" },
      { phrase: "good boy", linked: "goob boy", note: "/d/ → /b/ before /b/" },
      {
        phrase: "that case",
        linked: "thak case",
        note: "/t/ → /k/ before /k/",
      },
    ],
  },
  {
    feature: "Weak Forms",
    emoji: "🔉",
    description:
      "Function words are reduced to the schwa /ə/ in unstressed positions in natural speech.",
    examples: [
      { phrase: "can", linked: "/kən/", note: "strong: /kæn/, weak: /kən/" },
      {
        phrase: "and",
        linked: "/ənd/ or /ən/",
        note: "bread and butter → /brɛd ən ˈbʌtər/",
      },
      {
        phrase: "for",
        linked: "/fər/",
        note: "waiting for you → /ˈweɪtɪŋ fər juː/",
      },
    ],
  },
];
