// @ts-nocheck
/* eslint-disable */
export const VOCAB = [
  // ── General (Usable across all tasks) ──
  { word: "Initially", meaning: "At first; replaces the overused at the beginning", example: "Initially, I was nervous, but gradually I grew confident.", type: "General", task: "0" },
  { word: "Gradually", meaning: "Slowly over time; shows a process unfolding", example: "Gradually, I realized that hard work was paying off.", type: "General", task: "0" },
  { word: "Subsequently", meaning: "After that; more formal than then", example: "I completed my degree, and subsequently, I started working.", type: "General", task: "0" },
  { word: "Nevertheless", meaning: "Despite that; stronger contrast than but", example: "The weather was terrible; nevertheless, we went ahead with the plan.", type: "General", task: "0" },
  { word: "In hindsight", meaning: "Looking back now; great for closing reflections", example: "In hindsight, I wish I had started learning languages earlier.", type: "General", task: "0" },
  { word: "Ultimately", meaning: "In the end; finally", example: "Ultimately, the decision was mine to make.", type: "General", task: "0" },
  { word: "Perspective", meaning: "A particular way of viewing things", example: "From my perspective, this is the best approach.", type: "General", task: "0" },
  { word: "Significant", meaning: "Important or noticeable", example: "That experience had a significant impact on my life.", type: "General", task: "0" },
  { word: "Evident", meaning: "Clearly seen or understood", example: "Looking back, it was evident that moving abroad had changed me for the better.", type: "General", task: "0" },
  { word: "Remarkable", meaning: "Worthy of attention; striking", example: "What stood out most to me was the remarkable kindness of the people I met there.", type: "General", task: "0" },

  // ── Task 1: Giving Advice ──
  { word: "That must be difficult/stressful/challenging", meaning: "Shows understanding and empathy for the person's situation", example: "That must be stressful for you, balancing so many responsibilities at once.", type: "Empathy & Understanding", task: "1" },
  { word: "I understand/appreciate how you feel", meaning: "Connects emotionally and validates their feelings", example: "I understand how frustrating that is when you've been working so hard.", type: "Empathy & Understanding", task: "1" },
  { word: "I'm confident you can", meaning: "Encouragement and belief in their ability to succeed", example: "I'm confident you can find a solution that works for your situation.", type: "Empathy & Understanding", task: "1" },
  { word: "I would recommend/suggest", meaning: "Professional and formal way to give suggestions", example: "I would recommend talking to your manager about flexible working arrangements.", type: "Suggestions & Advice", task: "1" },
  { word: "In your situation, I would", meaning: "Personalized advice that shows you understand their specific context", example: "In your situation, I would prioritize getting enough sleep before anything else.", type: "Suggestions & Advice", task: "1" },
  { word: "I think/I believe you should", meaning: "Gentle, humble way to offer advice without being preachy", example: "I think you should give yourself more credit for what you've already accomplished.", type: "Suggestions & Advice", task: "1" },
  { word: "Because/Since/As", meaning: "Introduces reasoning and explains why advice will help", example: "You should create a schedule because it will help you manage your time better.", type: "Reasoning & Explanation", task: "1" },
  { word: "This would help/benefit you by", meaning: "Shows the positive outcome or benefit of the suggestion", example: "This would help you by reducing stress and giving you a clearer plan to follow.", type: "Reasoning & Explanation", task: "1" },
  { word: "First/Second/Additionally/Also", meaning: "Transitions that connect multiple pieces of advice logically", example: "First, I'd create a schedule. Second, I would talk to your manager. Additionally, try to set aside time for yourself.", type: "Transitions & Connectors", task: "1" },
  { word: "To summarize/In summary", meaning: "Concluding phrases that recap main advice before ending", example: "To summarize, I think creating a schedule and having a conversation with your manager are your best options.", type: "Transitions & Connectors", task: "1" },
  { word: "Prudent", meaning: "Wise and careful in decision-making", example: "It's prudent to save money before making major purchases.", type: "Wisdom & Judgment", task: "1" },
  { word: "Remedy", meaning: "A solution to a problem; a treatment", example: "The best remedy for stress is regular exercise and adequate rest.", type: "Wisdom & Judgment", task: "1" },
  { word: "Elaborate", meaning: "To explain in detail or provide more information", example: "Can you elaborate on why you think that approach would work best?", type: "Wisdom & Judgment", task: "1" },
  { word: "Feasible", meaning: "Possible to do; practicable and achievable", example: "The plan is feasible if we have enough time and resources.", type: "Wisdom & Judgment", task: "1" },

  // ── Task 2: Personal Experience ──
  { word: "Exhilarating", meaning: "Thrilling and exciting; full of energy and joy", example: "Skydiving for the first time was absolutely exhilarating, and I've never felt so alive.", type: "Emotion & Reaction", task: "2" },
  { word: "Humbling", meaning: "Making you feel small in a meaningful way; teaches perspective", example: "Volunteering was a humbling experience that made me realize how much I had to learn.", type: "Emotion & Reaction", task: "2" },
  { word: "Apprehensive", meaning: "Slightly anxious or worried, unsure of what's coming", example: "I felt apprehensive before my first day at university, but it turned out to be amazing.", type: "Emotion & Reaction", task: "2" },
  { word: "Awestruck", meaning: "Overwhelmed by something impressive, beautiful, or breathtaking", example: "We were completely awestruck when we saw the Northern Lights dancing across the sky.", type: "Emotion & Reaction", task: "2" },
  { word: "Relieved", meaning: "Free from worry or stress after something stressful resolves", example: "When I passed the exam, I felt completely relieved and could finally relax.", type: "Emotion & Reaction", task: "2" },
  { word: "Poignant", meaning: "Evoking sadness or regret; deeply moving or touching", example: "The film had a poignant ending that made me think about my own life choices.", type: "Emotion & Reaction", task: "2" },
  { word: "Shortly after", meaning: "A useful transition phrase for moving from opening to the main event", example: "Shortly after arriving, I realized that everything I thought I knew was about to change.", type: "Transition & Narrative", task: "2" },
  { word: "In that moment", meaning: "Creates immediacy and focus on a specific, important instance", example: "In that moment, when I reached the summit, everything I'd worked for felt worth it.", type: "Transition & Narrative", task: "2" },
  { word: "Looking back", meaning: "Perfect transition for closing; signals reflection and perspective", example: "Looking back, that trip showed me I'm more capable than I ever thought possible.", type: "Transition & Narrative", task: "2" },
  { word: "The air smelled of...", meaning: "Olfactory sensory detail that's rare and very memorable to listeners", example: "The air smelled like pine and rain, which brought back memories of my childhood.", type: "Sensory Detail", task: "2" },
  { word: "My hands were shaking", meaning: "Physical sensation detail that shows emotion without saying it directly", example: "My hands were shaking as I stepped forward to receive the award, which was nerve-wracking.", type: "Sensory Detail", task: "2" },
  { word: "It taught me...", meaning: "Standard closing frame that connects experience to personal growth or learning", example: "It taught me that I'm capable of more than I thought, and I'm grateful for that.", type: "Closing & Reflection", task: "2" },
  { word: "I'd do it again", meaning: "Simple, strong way to end a story that shows confidence and no regrets", example: "It wasn't easy, but I came out more confident — and I'd do it again in a heartbeat.", type: "Closing & Reflection", task: "2" },
  { word: "Immersive", meaning: "Completely surrounding you; fully engaging or absorbing experience", example: "The museum created an immersive experience with interactive displays that made me feel like I was there.", type: "Describing the Experience", task: "2" },
  { word: "Spontaneous", meaning: "Unplanned, happening naturally in the moment without prior arrangement", example: "We made a spontaneous decision to drive to the coast, and it became my favorite memory.", type: "Describing the Experience", task: "2" },
  { word: "Surreal", meaning: "Felt strange or dreamlike; almost too good or too odd to be real", example: "Meeting my favorite celebrity felt completely surreal, like I was living in a dream.", type: "Describing the Experience", task: "2" },
  { word: "Reminisce", meaning: "To recall and think fondly about past experiences and memories", example: "We spent the evening reminiscing about our university days and laughing at old stories.", type: "Reflection & Lessons", task: "2" },
  { word: "Pivotal", meaning: "A turning point or crucial moment that changed your life significantly", example: "That conversation was a pivotal moment in my career, and everything changed after that.", type: "Reflection & Lessons", task: "2" },
  { word: "Transformative", meaning: "Changed you in a deep, meaningful way; altered your perspective or abilities", example: "The program was transformative for my development, and I'm a different person because of it.", type: "Reflection & Lessons", task: "2" },
  { word: "Gratifying", meaning: "Deeply satisfying and rewarding; gives a sense of accomplishment", example: "Seeing my hard work pay off was incredibly gratifying, and it motivated me to keep going.", type: "Reflection & Lessons", task: "2" },

  // ── Task 3: Describing a Scene ──
  { word: "In the foreground", meaning: "The closest/nearest part of the image", example: "In the foreground, I can see children playing in the park.", type: "Spatial Language", task: "3" },
  { word: "In the background", meaning: "The farthest/rear part of the image", example: "In the background, mountains are visible against the sky.", type: "Spatial Language", task: "3" },
  { word: "In the center", meaning: "The middle of the image", example: "In the center, there's a large fountain with water flowing.", type: "Spatial Language", task: "3" },
  { word: "Surrounding", meaning: "Describing things around or within other things", example: "The buildings surrounding the plaza are all historic structures.", type: "Spatial Language", task: "3" },
  { word: "Nestled", meaning: "Positioned snugly within a surrounding area", example: "Buildings nestled among the trees create a peaceful village scene.", type: "Spatial Language", task: "3" },
  { word: "Vibrant", meaning: "Bright, vivid, and full of energy", example: "The market has vibrant red and yellow colors that catch the eye.", type: "Color & Description", task: "3" },
  { word: "Vivid", meaning: "Bright and striking in appearance", example: "The vivid blue of the ocean contrasts beautifully with the white sand.", type: "Color & Description", task: "3" },
  { word: "Muted", meaning: "Soft, subtle, or understated in color", example: "The sky displayed muted tones of gray and soft blue.", type: "Color & Description", task: "3" },
  { word: "Dull", meaning: "Not bright or vivid in color", example: "The dull brown walls of the old building gave it a somber feeling.", type: "Color & Description", task: "3" },
  { word: "Pale", meaning: "Light in color, lacking intensity", example: "The pale pink sunset was reflected in the calm water.", type: "Color & Description", task: "3" },
  { word: "Bustling", meaning: "Full of busy or noisy activity and energy", example: "The bustling marketplace is crowded with vendors and shoppers moving in all directions.", type: "Atmosphere & Mood", task: "3" },
  { word: "Lively", meaning: "Full of activity and enthusiasm; animated", example: "The lively street fair had music, dancing, and happy crowds everywhere.", type: "Atmosphere & Mood", task: "3" },
  { word: "Serene", meaning: "Calm, peaceful, and undisturbed", example: "The serene lake in early morning creates a sense of tranquility and rest.", type: "Atmosphere & Mood", task: "3" },
  { word: "Peaceful", meaning: "Free from disturbance or conflict", example: "The peaceful garden with its quiet paths offers a retreat from the city.", type: "Atmosphere & Mood", task: "3" },
  { word: "Tranquil", meaning: "Calm and quiet; undisturbed", example: "The tranquil countryside landscape evokes a feeling of absolute stillness.", type: "Atmosphere & Mood", task: "3" },
  { word: "Chaotic", meaning: "In a state of complete disorder and confusion", example: "The chaotic scene at the train station showed people rushing everywhere.", type: "Atmosphere & Mood", task: "3" },
  { word: "Hectic", meaning: "Full of activity and excitement, often stressfully so", example: "The hectic office environment with constant noise and movement was overwhelming.", type: "Atmosphere & Mood", task: "3" },
  { word: "Strolling", meaning: "Walking in a leisurely, relaxed way (present continuous: are strolling)", example: "People are strolling along the boardwalk, enjoying the nice weather.", type: "Action & Movement", task: "3" },
  { word: "Wandering", meaning: "Moving aimlessly or without a fixed course (present continuous: are wandering)", example: "Visitors are wandering through the historic streets, exploring the old district.", type: "Action & Movement", task: "3" },
  { word: "Gathered", meaning: "Assembled or collected together in a group (present continuous: are gathered)", example: "People are gathered around the fountain, taking photos and chatting.", type: "Action & Movement", task: "3" },
  { word: "Adjacent", meaning: "Next to or adjoining something else", example: "The hotel is adjacent to the beach, offering easy access to the water.", type: "Describing Places & Scenes", task: "3" },
  { word: "Picturesque", meaning: "Visually attractive and charming in appearance", example: "The picturesque village with its stone cottages and cobblestone streets is stunning.", type: "Describing Places & Scenes", task: "3" },
  { word: "Sprawling", meaning: "Spreading over a large area in an extended way", example: "The sprawling garden covers several acres with trees, flowers, and pathways.", type: "Describing Places & Scenes", task: "3" },
  { word: "Desolate", meaning: "Empty, barren, and often lonely in appearance", example: "The desolate beach in early morning, with no one around, felt peaceful and isolated.", type: "Describing Places & Scenes", task: "3" },
  { word: "Crowded", meaning: "Filled with many people, often uncomfortably so", example: "The crowded marketplace is packed with shoppers moving between different stalls.", type: "Describing Places & Scenes", task: "3" },

  // ── Task 4: Making Predictions ──
  { word: "If... then...", meaning: "Logical structure for stating hypothetical outcomes with clear cause and effect", example: "If someone loses their job suddenly, then they would likely face financial stress and need to update their resume.", type: "Conditional Structure", task: "4" },
  { word: "Will likely", meaning: "Express a confident prediction with reasonable certainty about a future outcome", example: "This will likely result in higher demand for services and increase competition in the market.", type: "Predictive Language", task: "4" },
  { word: "Would", meaning: "Use in conditional sentences to express hypothetical outcomes or consequences", example: "If X happens, Y would occur, and this would lead to significant changes in the industry.", type: "Conditional Structure", task: "4" },
  { word: "Might / Could", meaning: "Express uncertain or possible outcomes when the future is less certain", example: "It might lead to job losses, or it could result in the creation of new positions in other sectors.", type: "Predictive Language", task: "4" },
  { word: "Probably / Likely / Unlikely", meaning: "Indicate the degree of certainty for a prediction on a scale from probable to unlikely", example: "It's unlikely that prices will decrease, but it's probably going to change how consumers shop online.", type: "Likelihood Indicators", task: "4" },
  { word: "As a result", meaning: "Link a prediction directly to its logical consequence and expected impact", example: "As a result of climate change, unemployment might rise due to shifting economic sectors and job availability.", type: "Consequence Language", task: "4" },
  { word: "I predict that...", meaning: "Explicitly state a forecast or expected outcome with confidence and clarity", example: "I predict that companies will invest more in artificial intelligence to improve productivity and reduce costs.", type: "Predictive Language", task: "4" },
  { word: "In the event that", meaning: "Introduce hypothetical circumstances formally and set up conditional predictions", example: "In the event that interest rates drop, we would likely see increased housing demand and economic growth.", type: "Conditional Structure", task: "4" },
  { word: "It's unlikely / It's improbable", meaning: "State predictions with lower probability when outcomes are less probable", example: "It's unlikely that prices will decrease significantly, but it's improbable that demand will remain the same.", type: "Likelihood Indicators", task: "4" },
  { word: "This would lead to...", meaning: "Explain the logical outcome or consequence of a prediction clearly", example: "This would lead to better work-life balance for employees and potentially increase company retention rates.", type: "Consequence Language", task: "4" },
  { word: "Anticipate", meaning: "To expect or predict something based on current trends or evidence", example: "I anticipate that technology will transform industries within the next five years.", type: "Predictive Language", task: "4" },
  { word: "Inevitable", meaning: "Certain to happen; unavoidable; will definitely occur", example: "Change is inevitable in a fast-moving world, and companies must adapt or fail.", type: "Likelihood Indicators", task: "4" },
  { word: "Plausible", meaning: "Seeming reasonable or probable; credible and believable", example: "The explanation seems plausible, but I would argue that external factors matter more.", type: "Logic & Reasoning", task: "4" },
  { word: "Emerging", meaning: "Beginning to appear or become known; newly appearing trends or technologies", example: "Emerging technologies are reshaping society, and this trend will likely accelerate.", type: "Predictive Language", task: "4" },
  { word: "Trajectory", meaning: "The path or direction something is following; the expected course or trend", example: "The company's growth trajectory is impressive, and I predict it will continue upward.", type: "Logic & Reasoning", task: "4" },
  { word: "Accelerate", meaning: "To increase in speed or intensity; to happen faster than currently", example: "Climate change will accelerate if we don't act, and this would lead to severe environmental consequences.", type: "Consequence Language", task: "4" },

  // ── Task 5: Comparing & Persuading ──
  { word: "In contrast to", meaning: "Shows clear differences and contrasts between two options or perspectives", example: "In contrast to public transit, cars offer individual flexibility and personalized routes.", type: "Comparison Language", task: "5" },
  { word: "While / Whereas", meaning: "Compares two things by introducing contrast; shows what one has that the other lacks", example: "While option A is cheaper, option B is more sustainable and environmentally friendly.", type: "Comparison Language", task: "5" },
  { word: "Similarly", meaning: "Shows similarities and common ground between two options", example: "Similarly, both options require initial investment before you see long-term benefits.", type: "Comparison Language", task: "5" },
  { word: "It is crucial that", meaning: "Emphasizes the importance of a factor or consideration in your argument", example: "It is crucial that we prioritize sustainability when making decisions about transportation.", type: "Persuasion Language", task: "5" },
  { word: "Undeniably", meaning: "Strong assertion that emphasizes indisputable facts and cannot be argued against", example: "This is undeniably the better choice when you consider cost and environmental impact.", type: "Persuasion Language", task: "5" },
  { word: "Superior to", meaning: "Shows preference and indicates one option is better than another", example: "This option is superior to the alternative because it combines affordability with sustainability.", type: "Persuasion Language", task: "5" },
  { word: "The primary reason", meaning: "Introduces and emphasizes the main argument or most important factor", example: "The primary reason I choose public transit is its significant environmental benefits.", type: "Reasoning Language", task: "5" },
  { word: "This means that", meaning: "Draws conclusions and explains the logical consequence of what you just said", example: "This means that long-term savings are significant and will benefit your budget.", type: "Reasoning Language", task: "5" },
  { word: "Furthermore", meaning: "Adds another supporting point to strengthen your argument progressively", example: "Furthermore, reliability is also important, and this option proves more dependable over time.", type: "Transition Language", task: "5" },
  { word: "In conclusion", meaning: "Signals the closing of your argument and summarizes your position firmly", example: "In conclusion, the evidence supports this choice, making it the optimal decision.", type: "Transition Language", task: "5" },
  { word: "Whereas", meaning: "In contrast to; on the other hand", example: "Whereas my brother enjoys sports, I prefer reading and learning from books.", type: "Comparison Language", task: "5" },
  { word: "Moreover", meaning: "In addition; furthermore; adds another supporting point", example: "The job offers great salary. Moreover, benefits are excellent and the team is supportive.", type: "Persuasion Language", task: "5" },
  { word: "Analogous", meaning: "Comparable in certain respects; similar in meaningful ways", example: "Learning languages is analogous to learning music — both require practice and repetition.", type: "Comparison Language", task: "5" },
  { word: "Diverge", meaning: "To differ or move in different directions; to have opposing views", example: "Our opinions on education diverge significantly, but both have merit.", type: "Comparison Language", task: "5" },
  { word: "Compelling", meaning: "Convincing and persuasive; forces agreement through strong evidence", example: "The documentary presents a compelling argument that changed my perspective.", type: "Persuasion Language", task: "5" },
  { word: "Contend", meaning: "To argue or claim firmly and confidently", example: "I would contend that public transit is the more responsible choice for a growing city.", type: "Reasoning Language", task: "5" },
  { word: "Substantiate", meaning: "To support with evidence or proof; to back up claims with data", example: "I can substantiate my choice with clear benefits: lower costs, greater reliability, and long-term savings.", type: "Reasoning Language", task: "5" },

  // ── Task 6: Difficult Situation ──
  { word: "To acknowledge", meaning: "Recognize the problem. Shows responsibility and awareness", example: "I would acknowledge the mistake immediately.", type: "Problem Recognition", task: "6" },
  { word: "Unforeseen circumstances", meaning: "Unexpected events. Shows that challenges can arise despite planning", example: "Due to unforeseen circumstances, the plan had to be adjusted.", type: "Problem Recognition", task: "6" },
  { word: "Predicament", meaning: "A difficult, complicated, or embarrassing situation", example: "I found myself in a predicament when my car broke down.", type: "Problem Recognition", task: "6" },
  { word: "Dilemma", meaning: "A situation with two equally difficult options", example: "I faced a dilemma: accept the job or stay close to family.", type: "Problem Recognition", task: "6" },
  { word: "To take initiative", meaning: "Act without waiting for permission or guidance. Shows proactive problem-solving", example: "I would take initiative to solve it immediately.", type: "Action & Problem-solving", task: "6" },
  { word: "To communicate transparently", meaning: "Be open and honest. Shows professionalism and trust", example: "I would communicate transparently with my team about the issue.", type: "Action & Problem-solving", task: "6" },
  { word: "To mitigate the issue", meaning: "Reduce the damage or impact of a problem. Shows damage control", example: "I would mitigate the issue by taking immediate corrective action.", type: "Action & Problem-solving", task: "6" },
  { word: "To propose a solution", meaning: "Offer a way to fix it. Shows problem-solving capability", example: "I would propose a solution to prevent future occurrences.", type: "Action & Problem-solving", task: "6" },
  { word: "Composed", meaning: "Calm and in control. Shows emotional maturity under pressure", example: "I would remain composed and handle the situation professionally.", type: "Emotion & Composure", task: "6" },
  { word: "Resilience", meaning: "Ability to recover and keep going after setbacks", example: "I drew on my resilience to stay calm and work through the problem one step at a time.", type: "Emotion & Composure", task: "6" },
  { word: "To learn from experience", meaning: "Gain wisdom from setbacks. Shows growth mindset", example: "I would learn from the experience to prevent it happening again.", type: "Reflection & Learning", task: "6" },
  { word: "To prevent future occurrences", meaning: "Stop it from happening again. Shows foresight and responsibility", example: "I would implement steps to prevent future occurrences.", type: "Reflection & Learning", task: "6" },

  // ── Task 7: Expressing Opinions ──
  { word: "I believe", meaning: "States opinion clearly and confidently", example: "I believe education is the foundation of success.", type: "Opinion Statement", task: "7" },
  { word: "In my view", meaning: "Personal perspective; introduces personal opinion", example: "In my view, technology has transformed our lives.", type: "Opinion Statement", task: "7" },
  { word: "Strongly believe", meaning: "Expresses confident and firm opinion", example: "I strongly believe this approach works best.", type: "Opinion Statement", task: "7" },
  { word: "This is because", meaning: "Introduces reasoning and explanation for opinion", example: "This is because experience builds wisdom.", type: "Reasoning & Evidence", task: "7" },
  { word: "For example", meaning: "Introduces specific evidence or example", example: "For example, many young entrepreneurs start ventures early.", type: "Reasoning & Evidence", task: "7" },
  { word: "Demonstrates", meaning: "Shows connection between evidence and opinion", example: "This demonstrates the importance of critical thinking.", type: "Reasoning & Evidence", task: "7" },
  { word: "Undoubtedly", meaning: "Shows confidence and certainty about opinion", example: "Undoubtedly, mental health is crucial.", type: "Emphasis & Confidence", task: "7" },
  { word: "It is clear that", meaning: "Strong assertion that shows conviction", example: "It is clear that climate action is urgent.", type: "Emphasis & Confidence", task: "7" },
  { word: "In conclusion", meaning: "Signals closing and final summary of opinion", example: "In conclusion, my opinion is well-founded.", type: "Closing", task: "7" },
  { word: "To summarize", meaning: "Wraps up main points and restates position", example: "To summarize, these three factors support my view.", type: "Closing", task: "7" },

  // ── Task 8: Describing an Unusual Situation (describe an odd picture to someone who can't see it) ──
  { word: "At first glance", meaning: "Opens your overview before you get into the details", example: "At first glance, it looks like an ordinary chair, but it has wheels where the legs should be.", type: "Overview & First Impression", task: "8" },
  { word: "It appears to be", meaning: "Hedging phrase for describing something you can't fully identify", example: "It appears to be some kind of machine, though I've never seen anything quite like it.", type: "Overview & First Impression", task: "8" },
  { word: "Peculiar", meaning: "Strange or unusual in a noticeable way", example: "The most peculiar thing in the picture is a clock with no numbers on its face.", type: "Overview & First Impression", task: "8" },
  { word: "Bizarre", meaning: "Very strange; odd to the point of surprising", example: "It's a bizarre contraption that seems to combine a bicycle with a kitchen table.", type: "Overview & First Impression", task: "8" },
  { word: "Cylindrical", meaning: "Shaped like a cylinder or tube", example: "The main part is cylindrical, roughly like a large soup can standing upright.", type: "Shape & Size", task: "8" },
  { word: "Irregular", meaning: "Not even or symmetrical in shape", example: "The top has an irregular shape, with one side much taller than the other.", type: "Shape & Size", task: "8" },
  { word: "Roughly the size of", meaning: "Compares the object's size to something familiar", example: "It's roughly the size of a microwave, so it would just fit on a kitchen counter.", type: "Shape & Size", task: "8" },
  { word: "Resembles", meaning: "Looks like something else; useful for comparisons", example: "The handle resembles a question mark, curving back on itself at the top.", type: "Shape & Size", task: "8" },
  { word: "Transparent", meaning: "Clear; you can see through it", example: "The container is transparent, so you can see the wires coiled up inside it.", type: "Colour & Material", task: "8" },
  { word: "Metallic", meaning: "Made of metal or shiny like metal", example: "It has a metallic surface that reflects the light, probably steel or aluminum.", type: "Colour & Material", task: "8" },
  { word: "Worn", meaning: "Faded or damaged from age and use", example: "The wooden base looks worn, with chipped paint along the edges.", type: "Colour & Material", task: "8" },
  { word: "Seems to be used for", meaning: "Guesses the purpose of an unfamiliar object", example: "It seems to be used for cleaning, since there's a brush attached to one end.", type: "Function & Purpose", task: "8" },
  { word: "Contraption", meaning: "An odd or overly complicated device", example: "The whole contraption is covered in buttons and levers, but it's not clear what they do.", type: "Function & Purpose", task: "8" },
  { word: "What's odd about it is", meaning: "Frames the strange detail that makes the picture unusual", example: "What's odd about it is that a bird's nest is sitting right on top of the device.", type: "Function & Purpose", task: "8" },

  // ── Writing Task 1: Email Writing ──
  { word: "I am writing to", meaning: "Classic opening for stating your purpose clearly", example: "I am writing to request an extension on the deadline.", type: "Email Opening", task: "W1" },
  { word: "I would like to inquire about", meaning: "Professional way to ask questions politely", example: "I would like to inquire about the availability of the position.", type: "Email Opening", task: "W1" },
  { word: "Furthermore / In addition", meaning: "Add another supporting point to strengthen argument", example: "In addition, I have five years of experience in this field.", type: "Linking Words", task: "W1" },
  { word: "As a result / Consequently", meaning: "Show cause and effect relationships clearly", example: "As a result, I believe I am the right candidate.", type: "Linking Words", task: "W1" },
  { word: "However / Nevertheless", meaning: "Introduce a contrasting or opposing idea", example: "However, I do have some questions about the timeline.", type: "Linking Words", task: "W1" },
  { word: "I would appreciate it if", meaning: "Very polite way to make a request", example: "I would appreciate it if you could send me the updated schedule.", type: "Polite Language", task: "W1" },
  { word: "Could you please", meaning: "Polite request phrasing that shows respect", example: "Could you please provide feedback by Friday?", type: "Polite Language", task: "W1" },
  { word: "With regard to / Regarding", meaning: "Professional way to reference a specific topic", example: "Regarding your earlier email, I have some concerns.", type: "Polite Language", task: "W1" },
  { word: "Thank you for your", meaning: "Express gratitude politely and professionally", example: "Thank you for your time and consideration.", type: "Email Closing", task: "W1" },
  { word: "I look forward to", meaning: "Show positive anticipation about future communication", example: "I look forward to hearing from you soon.", type: "Email Closing", task: "W1" },

  // ── Writing Task 2: Essay Writing ──
  { word: "It is clear that", meaning: "State your position confidently and definitively", example: "It is clear that government action is necessary.", type: "Thesis Statement", task: "W2" },
  { word: "I believe that / I argue that", meaning: "Classic thesis phrasing that shows personal stance", example: "I believe that education should be free for all.", type: "Thesis Statement", task: "W2" },
  { word: "One could argue that", meaning: "Introduce a supporting argument thoughtfully to show nuance", example: "One could argue that innovation drives economic growth.", type: "Argument Development", task: "W2" },
  { word: "It is essential that / It is vital that", meaning: "Emphasize the importance of a point or action", example: "It is essential that we take action now.", type: "Argument Development", task: "W2" },
  { word: "To summarize / In conclusion", meaning: "Introduce your final paragraph and recap main points", example: "To summarize, the evidence strongly supports this position.", type: "Argument Development", task: "W2" },
  { word: "For example / For instance", meaning: "Introduce specific examples or concrete evidence", example: "For example, research shows that exercise improves mental health.", type: "Transition Words", task: "W2" },
  { word: "Furthermore / Moreover / In addition", meaning: "Add supporting points to strengthen your argument", example: "Furthermore, the economic impact cannot be ignored.", type: "Transition Words", task: "W2" },
  { word: "In contrast / However / Nevertheless", meaning: "Present opposing views or acknowledge counterarguments", example: "However, this approach has significant limitations.", type: "Transition Words", task: "W2" },
  { word: "This demonstrates that", meaning: "Connect evidence directly to your argument", example: "This demonstrates the effectiveness of the proposed policy.", type: "Evidence Integration", task: "W2" },
  { word: "As a result / Consequently / Therefore", meaning: "Show clear cause-and-effect relationships", example: "As a result, the proposal should be implemented immediately.", type: "Evidence Integration", task: "W2" },
];
